### ISSUE TITLE
python@3.8.4: decompress error

### ISSUE THREAD

**Issue by macoro** [ScoopInstaller/Main#1271]
setup.exe
dark.exe : error DARK0001 : Access to the path '~\scoop\apps\python\3.8.4\_tmp\AttachedContainer\py.exe' is denied.

Exception Type: System.UnauthorizedAccessException

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)

**Comment by macoro** [comment]
Error installing python
