### ISSUE TITLE
netcat@1.12: Download failed

### ISSUE THREAD

**Issue by CoolingTool** [ScoopInstaller/Main#2236]
Unable to connect to the remote server
```
PS C:\Program Files> scoop install netcat
Installing 'netcat' (1.12) [64bit] [main]
WARN  By installing you accept following license: GPL-2.0-only (https://spdx.org/licenses/GPL-2.0-only.html)
ERROR System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 84.255.206.8:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
ERROR Unable to connect to the remote server

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=netcat%401.12%3a+Download+failed&body=Unable+to+connect+to+the+remote+server
```

**Comment by Erisa** [comment]
This works now, and should be rechecked/closed

**Comment by rashil2000** [comment]
Yes, works on my end. 

Thanks for the reminder @Erisa :)
