### ISSUE TITLE
7zip@19.00: decompress error

### ISSUE THREAD

**Issue by zoof** [ScoopInstaller/Main#2566]
Unable to install 7zip:

scoop\apps\7zip\19.00\msi.log:
```
Extracting 'C:\Users\username\scoop\apps\7zip\19.00\7z1900-x64.msi' to 'C:\Users\username\scoop\apps\7zip\19.00\_tmp\'.
1/102   7zFM.exe
2/102   7-zip32.dll
3/102   7-zip.dll
4/102   7zG.exe
5/102   7z.dll
6/102   7z.exe
7/102   7z.sfx
8/102   7zCon.sfx
9/102   descript.ion
10/102  History.txt
11/102  License.txt
12/102  readme.txt
13/102  7-zip.chm
14/102  en.ttt

Error: System.Exception: Error 'MSPACK_ERR_OPEN' extracting file to \\?\C:\Users\username\scoop\apps\7zip\19.00\_tmp\SourceDir\Files\7-Zip\Lang\en.ttt.
   at LibMSPackN.MSCompressedFile.ExtractTo(String destinationFilename)
   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, List`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)

Usage:
lessmsi <command> [options] <msi_name> [<path_to_extract\>] [file_names]

Commands:
  x  Extracts all or specified files from the specified msi_name.
  l  Lists the contents of the specified msi table as CSV to stdout. Table is
     specified with -t switch. Example: lessmsi l -t Component c:\foo.msi
  v  Lists the value of the ProductVersion Property in the msi
     (typically this is the version of the MSI).
  o  Opens the specified msi_name in the GUI.
  h  Shows this help page.

For more information see http://lessmsi.activescott.com
```

**Comment by manchoz** [comment]
Please, see https://github.com/ScoopInstaller/Main/issues/17

**Comment by rashil2000** [comment]
7zip is updated to 21.07 now
