### ISSUE TITLE
Errors installing heroku-cli

### ISSUE THREAD

**Issue by tomihawk** [ScoopInstaller/Main#2617]
I'm getting the following error when installing heroku-cli.  Tried regular and global installs with regular and admin privileges but always the same result (extra errors when running without admin rights).

```
C:\WINDOWS\system32>scoop install -g heroku-cli
Installing 'heroku-cli' (7.59.0) [64bit]
heroku-win32-x64.tar.xz (15.4 MB) [===========================================================================] 100%
Checking hash of heroku-win32-x64.tar.xz ... ok.
Extracting dl.xz ... done.
Running pre-install script...
Move-Item : Access to the path 'C:\ProgramData\scoop\apps\heroku-cli\7.59.0\dlo\heroku\node_modules' is denied.
At line:9 char:1
+ Move-Item "$dir\dlo\heroku\*" "$dir"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\ProgramData\...ku\node_modules:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

Linking C:\ProgramData\scoop\apps\heroku-cli\current => C:\ProgramData\scoop\apps\heroku-cli\7.59.0
Creating shim for 'heroku'.
Adding C:\ProgramData\scoop\shims to global path.
'heroku-cli' (7.59.0) was installed successfully!
```
Even though it claims to be installed successfully it doesn't run
```
D:\>heroku
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@oclif/command'
Require stack:
- C:\ProgramData\scoop\apps\heroku-cli\7.59.0\bin\run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\ProgramData\scoop\apps\heroku-cli\7.59.0\bin\run:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\ProgramData\\scoop\\apps\\heroku-cli\\7.59.0\\bin\\run' ]
}
```
Checked my Sophos logs and it doesn't seem to be blocked by virus/malware protection.

Anyone seeing similar or got any ideas?

**Comment by tomihawk** [comment]
Not happening now.  Don't know if it's been fixed or something happened on my end.
