### ISSUE TITLE
Error running `firebase`

### ISSUE THREAD

**Issue by patevs** [ScoopInstaller/Main#3246]
## Bug Report

**firebase**

### Current Behaviour

`firebase` installs successfully but throws an error when run.

### Expected Behaviour

`firebase` command executes without error.

### Additional context/output

```powershell
> firebase --help
pkg/prelude/bootstrap.js:1359
      throw error;
      ^

Error: Cannot find module 'semver'
Require stack:
- C:\Users\User\.cache\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\.cache\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1394:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\.cache\\firebase\\tools\\lib\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ],
  pkg: true
}
```

### System details

**Windows version:** 10
**OS architecture:** 64bit
**PowerShell version:** 7.2.1

**Comment by rashil2000** [comment]
The GitHub release page of firebase-tools has 2 downloads for Windows, see here https://github.com/firebase/firebase-tools/releases:

![image](https://user-images.githubusercontent.com/46838874/150748391-2b662b0a-6e61-436c-b422-75cf40c33314.png)

Does your error occur on both the binaries?

**Comment by patevs** [comment]
Running the `firebase-tools-win.exe` binary produces the same error as above.

Running the `firebase-tools-instant-win.exe` binary throws the following error:

```
> .\firebase-tools-instant-win.exe --help
############################################################################################################################################################################################

     Welcome to...
   ######## #### ########  ######## ########     ###     ######  ########  ##
   ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##        ##
   ######    ##  ########  ######   ########  #########  ######  ######    ##
   ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
   ##       #### ##     ## ######## ########  ##     ##  ######  ########  ##


############################################################################################################################################################################################

~ Let's make sure your Firebase CLI is ready...
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\snapshot\firepit\welcome.js:115:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

So, this appears to be an issue with `firebase` itself.

**Comment by rashil2000** [comment]
Okay, please file an issue in their repository

**Comment by patevs** [comment]
Appears to be a known issue. See: 

[SyntaxError: Unexpected end of JSON input #3432](https://github.com/firebase/firebase-tools/issues/3432#issue-907209233)
[Error: Cannot find module 'semver' #2336](https://github.com/firebase/firebase-tools/issues/2336)

For reference, the following fixed the issue: https://github.com/firebase/firebase-tools/issues/2336#issuecomment-639816240

Regardless, closing this issue as not `scoop` related.

@rashil2000 Thank you for your help.

**Comment by rashil2000** [comment]
No worries :)
