### ISSUE TITLE
npm help <term> error invlid URL

### ISSUE THREAD

**Issue by dflock** [ScoopInstaller/Main#3607]
## Bug Report

**Package Name:** nodejs-lts 16.15.0

### Current Behaviour

If I run `npm help` it correctly outputs the basic useage to the console:

```
❯ npm help
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term> (in a browser)
npm help npm       more involved overview (in a browser)

All commands:

    access, adduser, audit, bin, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    hook, init, install, install-ci-test, install-test, link,
    ll, login, logout, ls, org, outdated, owner, pack, ping,
    pkg, prefix, profile, prune, publish, rebuild, repo,
    restart, root, run-script, search, set, set-script,
    shrinkwrap, star, stars, start, stop, team, test, token,
    uninstall, unpublish, unstar, update, version, view, whoami

Specify configs in the ini-formatted file:
    C:\Users\DuncanLock\.npmrc
or on the command line via: npm <command> --key=value

More configuration info: npm help config
Configuration fields: npm help 7 config

npm@8.1.2 C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm
```

However, if I run `npm help <term>` - for example `npm help install`, I get this error:

```
❯ npm help install
npm ERR! Invalid URL: file://C:%5CUsers%5CDuncanLock%5CAppData%5CRoaming%5Cnvm%5Cv16.13.2%5Cnode_modules%5Cnpm%5Cdocs%5Coutput%5Ccommands%5Cnpm-install.html

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DuncanLock\AppData\Local\npm-cache\_logs\2022-05-24T19_34_52_046Z-debug.log
```

### Expected Behaviour

I expect `npm help install` to work correctly, opening the help in a browser, rather than giving an error.

### Additional context/output

The contents of the debug log file mentioned are:

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'help',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\DuncanLock\dev\docs-automation\perforce-web-index\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\DuncanLock\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 15ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 26ms
27 timing command:help Completed in 8ms
28 verbose stack Error: Invalid URL: file://C:%5CUsers%5CDuncanLock%5CAppData%5CRoaming%5Cnvm%5Cv16.13.2%5Cnode_modules%5Cnpm%5Cdocs%5Coutput%5Ccommands%5Cnpm-install.html
28 verbose stack     at open (C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\lib\utils\open-url.js:31:11)
28 verbose stack     at Help.viewMan (C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\lib\help.js:130:15)
28 verbose stack     at Help.help (C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\lib\help.js:91:18)
29 verbose cwd C:\Users\DuncanLock\dev\docs-automation\perforce-web-index
30 verbose Windows_NT 10.0.19044
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "help" "install"
32 verbose node v16.13.2
33 verbose npm  v8.1.2
34 error Invalid URL: file://C:%5CUsers%5CDuncanLock%5CAppData%5CRoaming%5Cnvm%5Cv16.13.2%5Cnode_modules%5Cnpm%5Cdocs%5Coutput%5Ccommands%5Cnpm-install.html
35 verbose exit 1
```

### Possible Solution

The file it's trying to open exists and appears to be a valid HTML page:

```
❯ ll C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\docs\output\commands\npm-install.html

    Directory: C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\docs\output\commands

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2022-01-19  4:59 PM          34238 npm-install.html

❯ head C:\Users\DuncanLock\AppData\Roaming\nvm\v16.13.2\node_modules\npm\docs\output\commands\npm-install.html

<html><head>
<title>npm-install</title>
<style>
body {
    background-color: #ffffff;
    color: #24292e;

    margin: 0;

    line-height: 1.5;
```

The error is complaining about the URL, rather then the file: 

```
Error: Invalid URL: file://C:%5CUsers%5CDuncanLock%5CAppData%5CRoaming%5Cnvm%5Cv16.13.2%5Cnode_modules%5Cnpm%5Cdocs%5Coutput%5Ccommands%5Cnpm-install.html
```

If I paste that into a browser, I get same error. Fiddling about a bit, this version of the URL works fine in a browser:

```
file:///C:/Users/DuncanLock/AppData/Roaming/nvm/v16.13.2/node_modules/npm/docs/output/commands/npm-install.html
```

So, forward slashes and starting with `file:///`.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

**Additional software:** n/a

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-24T12:29:48.6754517-07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "alias": {
    "outdated": "scoop-outdated",
    "rm": "scoop-rm",
    "remove": "scoop-remove",
    "upgrade": "scoop-upgrade"
  }
}
```

**Comment by rashil2000** [comment]
You have a conflicting installation of nvm. 

The command works fine for me, and the file URL should point to somewhere in your Scoop directory instead of AppData.

Please uninstall all instances of Nodejs and reinstall Nodejs from Scoop
