### ISSUE TITLE
scoop update flutter  3.7.9 。Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dong-lufei** [ScoopInstaller/Main#4624]
```
$ scoop update flutter
flutter: 3.7.8 -> 3.7.9
Updating one outdated app:
Updating 'flutter' (3.7.8 -> 3.7.9)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: ffa42b|OK  |   442KiB/s|D:/scoop_user_apps/cache/flutter#3.7.9#https_raw.githubusercontent.com_ScoopInstaller_Extras_master_scripts_flutter-dev-setup.ps1
Download: 7b6cbc|OK  |    29MiB/s|D:/scoop_user_apps/cache/flutter#3.7.9#https_storage.googleapis.com_flutter_infra_release_releases_stable_windows_flutter_windows_3.7.9-stable.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of flutter_windows_3.7.9-stable.zip ... ok.
Checking hash of flutter-dev-setup.ps1 ... ok.
Uninstalling 'flutter' (3.7.8)
Removing shim 'flutter'.
Removing shim 'flutter.cmd'.
Removing shim 'flutter-dev-setup'.
Removing shim 'flutter-dev-setup.cmd'.
Removing shim 'flutter-dev-setup.ps1'.
Unlinking D:\scoop_user_apps\apps\flutter\current
Installing 'flutter' (3.7.9) [64bit] from extras bucket
Loading flutter_windows_3.7.9-stable.zip from cache.
Loading flutter-dev-setup.ps1 from cache.
Extracting flutter_windows_3.7.9-stable.zip ... done.
Linking D:\scoop_user_apps\apps\flutter\current => D:\scoop_user_apps\apps\flutter\3.7.9
Creating shim for 'flutter'.
Creating shim for 'flutter-dev-setup'.
Running post_install script...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema      ]
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
InvalidOperation: D:\scoop_user_apps\apps\flutter\current\flutter-dev-setup.ps1:119
Line |
 119 |  $platform_installed = ($installed_items | % {$_.Contains("platforms;" …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: D:\scoop_user_apps\apps\flutter\current\flutter-dev-setup.ps1:122
Line |
 122 |  $buildtools_installed = ($installed_items | % {$_.Contains("build-too …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
All required dependencies for Android Development are installed.
Some licenses need to be accepted before developing. It is recommended to do by running 'flutter doctor --android-licenses'.
```

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Extras/issues/10413
