### ISSUE TITLE
python@3.12.3: decompress error

### ISSUE THREAD

**Issue by HertogArjan** [ScoopInstaller/Main#5723]
```
python: 3.12.2 -> 3.12.3
Updating one outdated app:
Updating 'python' (3.12.2 -> 3.12.3)
Downloading new version
Loading python-3.12.3-amd64.exe from cache
Checking hash of python-3.12.3-amd64.exe ... ok.
Uninstalling 'python' (3.12.2)
Running uninstaller script...
Installing 'python' (3.12.3) [64bit] from 'main' bucket
Loading python-3.12.3-amd64.exe from cache
Running pre_install script...
Running installer script...
ERROR Exit code was 1639!
Failed to extract files from C:\Users\Jelle Jan\scoop\apps\python\3.12.3\_tmp\AttachedContainer\core.msi.
Log file:
  ~\scoop\apps\python\3.12.3\_tmp\AttachedContainer\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=python%403.12.3%3a+decompress+error
```

The file `msi.log` does not exist.

**Comment by HertogArjan** [comment]
```
PS C:\Users\Jelle Jan> scoop config use_lessmsi
'use_lessmsi' is not set
```
I suspect you meant to write `scoop config use_lessmsi $true`
```
PS C:\Users\Jelle Jan> scoop config use_lessmsi $true
'use_lessmsi' has been set to 'True'
```
With this setting the installation does succeed. There is still another error but it is unclear whether it is related and the installation appears to work fine afterwards.
```
PS C:\Users\Jelle Jan> scoop update python
ERROR 'python' isn't installed.
PS C:\Users\Jelle Jan> scoop install python@3.12.3
Installing 'lessmsi' (1.11.0) [64bit] from 'main' bucket
lessmsi-v1.11.0.zip (498,0 KB) [==============================================================================] 100%
Checking hash of lessmsi-v1.11.0.zip ... ok.
Extracting lessmsi-v1.11.0.zip ... done.
Linking ~\scoop\apps\lessmsi\current => ~\scoop\apps\lessmsi\1.11.0
Creating shim for 'lessmsi'.
Creating shortcut for Less MSIérables (lessmsi-gui.exe)
'lessmsi' (1.11.0) was installed successfully!
Installing 'python' (3.12.3) [64bit] from 'C:\Users\Jelle Jan\scoop\buckets\main\bucket\python.json'
python-3.12.3-amd64.exe (25,5 MB) [===========================================================================] 100%
Checking hash of python-3.12.3-amd64.exe ... ok.
Running pre_install script...
Running installer script...
Linking ~\scoop\apps\python\current => ~\scoop\apps\python\3.12.3
Creating shim for 'python3'.
Creating shim for 'idle'.
Creating shim for 'idle3'.
Adding ~\scoop\apps\python\current\Scripts to your path.
Adding ~\scoop\apps\python\current to your path.
Persisting Scripts
Persisting Lib\site-packages
Running post_install script...
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: 'C:\\Users\\Jelle Jan\\scoop\\apps\\python\\current\\Scripts\\pip.exe' -> 'C:\\Users\\Jelle Jan\\scoop\\apps\\python\\current\\Scripts\\pip.exe.deleteme'

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jelle Jan\scoop\apps\python\current\Lib\ensurepip\__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Jelle Jan\scoop\apps\python\current\Lib\ensurepip\__init__.py", line 284, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "C:\Users\Jelle Jan\scoop\apps\python\current\Lib\ensurepip\__init__.py", line 200, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jelle Jan\scoop\apps\python\current\Lib\ensurepip\__init__.py", line 101, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jelle Jan\scoop\apps\python\current\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Jelle Jan\\scoop\\apps\\python\\current\\python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'C:\\\\Users\\\\JELLEJ~2\\\\AppData\\\\Local\\\\Temp\\\\tmpbnmz1gjv\\\\pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'C:\\\\Users\\\\JELLEJ~2\\\\AppData\\\\Local\\\\Temp\\\\tmpbnmz1gjv\', \'--upgrade\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

'python' (3.12.3) was installed successfully!
Notes
-----
Allow applications and third-party installers to find python by running: "C:\Users\Jelle
Jan\scoop\apps\python\current\install-pep-514.reg"
```
